application: goyakaradios
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|css|ico)$)
  static_files: \1
  upload: (.*\.(gif|png|jpg|css|ico)$)

- url: /oauth2callback
  script: goyakaradios.app

- url: /initcronfetch
  script: goyakaradios.app
  login: admin

- url: /cronfetch
  script: goyakaradios.app
  login: admin

- url: /fetch
  script: goyakaradios.app
  login: admin

- url: /fetchworker
  script: goyakaradios.app
  login: admin

- url: /initdatastore
  script: goyakaradios.app
  login: admin

- url: /
  script: goyakaradios.app

libraries:
- name: webapp2
  version: latest
